name: tek_handle_race_condition
description: "Tek handle race condition."
version: 0.0.2
homepage: https://pub.dev/packages/tek_handle_race_condition

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: